### ISSUE TITLE
How do I add topic labels?

### ISSUE THREAD

**Issue by CShorten** [nomic-ai/cookbook#3]
Hey nomic team! I am testing the Weaviate script, all good on getting data from Weaviate into nomic!

I can't figure out from here how to add topic labels with maybe either the cluster document tf-idf thing from BERTopic or maybe some kind of summarization chain with an LLM where I would give an API key and so on.

Here is a picture of where I am at, any help on how to get the topic labels is really appreciated! Thanks! Atlas looks really cool, excited to work with this!
<img width="943" alt="PodcastNomicViz" src="https://github.com/nomic-ai/maps/assets/25864937/1b8c58d1-3d6a-4174-8168-b634b0e36cf5">

**Comment by AndriyMulyar** [comment]
Hi @CShorten !
If you specify topic_label_field='content' in your project.create_index call, it will auto generate topic labels!
Full documentation can be found here: https://docs.nomic.ai/atlas_api.html#nomic.project.AtlasProject.create_index

**Comment by CShorten** [comment]
Fantastic! Thanks Andriy!
